version: "3"

tasks:
  default:
    deps: [install, test]

  install:
    cmds:
      - |
        rustup component add clippy
        rustup component add rustfmt

  run: cargo run -- data/call_merger -y

  run_docker:
    cmds:
      - |
        docker build -t vidmerger .
        docker container run -it --rm -v ./data/call_merger:/data vidmerger

  exec: docker exec -it -w /workspaces/vidmerger devcontainer-vidmerger fish

  test: cargo test

  lint: cargo clippy
